---
- name: ensure systemd configuration is reloaded
  meta: flush_handlers

- name: ensure systemd service
  include_role:
    name: "damex.systemd"
  vars:
    systemd_services:
      - name: "{{ quassel_service_name }}"
        restart_on: "quassel_systemd_configuration.changed"
