---
- name: ensure systemd configuration is reloaded
  meta: flush_handlers

- name: ensure systemd service
  include_role:
    name: "damex.systemd_service"
  vars:
    systemd_service_name: "{{ quassel_service_name }}"
    systemd_service_restart_on: "{{ quassel_systemd_configuration.changed }}"
